name: vyuh
repository: https://github.com/vyuh-tech/vyuh

packages:
  - packages/*
  - packages/{sanity,}/*
  - features/*
  - apps/*

command:
  bootstrap:
    usePubspecOverrides: true

ide:
  intellij:
    moduleNamePrefix: ''
