name: vyuh_feature_developer
description: A new Flutter package project.
version: 1.0.0
homepage: https://vyuh.tech

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  vyuh_core: ^1.0.0
  go_router: ^13.0.1
  flutter_sticky_header: ^0.6.5
  vyuh_extension_content: ^1.0.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
