name: vyuh_cache
description: A generic caching package for Vyuh
version: 1.0.0

environment:
  sdk: ^3.1.0

dependencies:
  crypto: ^3.0.3
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^3.0.0
  test: ^1.21.0
  json_serializable: ^6.7.1
