name: vyuh_demo
description: A tech demo of the Vyuh Framework
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sanity_client: ^1.0.0-beta.2
  vyuh_core: ^1.0.0
  vyuh_extension_content: ^1.0.0
  vyuh_feature_developer: ^1.0.0
  feature_sample: ^1.0.0
  cupertino_icons: ^1.0.6
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
